services:
  frontend:
    build:
      context: frontend
      dockerfile: ./Dockerfile
  backend:
    build:
      context: backend
      dockerfile: ./Dockerfile
    restart: on-failure
  nginx:
    build:
      context: nginx
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
