FROM rust:trixie
WORKDIR /app
COPY ./ ./

RUN apt-get update && \
    apt-get install -y --no-install-recommends osmium-tool && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app/osm
RUN ./update-osm.sh

WORKDIR /app
RUN cargo install cargo-watch
EXPOSE 3000
CMD ["cargo", "watch", "-x", "run"]