server {
    listen 80;

    location /api/ {
        proxy_pass http://backend:3000;
    }

    location /ws {
        proxy_pass http://backend:3001;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }


    location / {
        proxy_pass http://frontend:5173;
        proxy_set_header Host $host;
    }
}
